hexojs/hexo-renderer-marked

package.json
=> Upgrade dependencies. Fixes DoS in marked.

lib/renderer.js, test/index.js
=> Strip html from headerlink title

README.md
modifyAnchors option have to specify `integer`.  (#79 )
=> chore(doc): update modifyAnchors explanation (#79)

test/index.js
=> test: sanitizeUrl and link with title

test/index.js
Continuation of https://github.com/hexojs/hexo-renderer-marked/pull/122
=> test(link): escape html

README.md, index.js, lib/renderer.js, test/index.js
Continuation of https://github.com/hexojs/hexo-renderer-marked/pull/116
=> feat(link): 'nofollow' option

lib/renderer.js, package.json, test/index.js
https://github.com/hexojs/hexo-util/pull/140
=> refactor: utilize isExternalLink() of hexo-util

test/index.js
=> test: heading with link & duplicate heading

README.md, index.js, test/index.js
current doc shows empty string as default, even though the value must be an integer.
=> fix(modifyAnchors): default to zero

README.md
https://github.com/hexojs/hexo-renderer-marked/pull/129
=> docs: marked:renderer filter

README.md, lib/renderer.js, test/index.js
Fixes #89 cc @Buzut 
Feature inspired by https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration#quotes.
=> feat: 'quotes' option to override smartypants

README.md, index.js, package.json
david-dm badge is replaced with more reliable shields.io.
=> release: 3.3.0

README.md
refs: https://github.com/hexojs/hexo-renderer-marked/pull/168
=> chore: update build badge on README

package.json
I will publish a new version after merge this PR.
Thank you :)
=> chore: release v4.1.0

README.md, index.js
=> Enable prependRoot by default

package.json
I'm going to release a new version after merge this PR.
Thank you :)
P.S:
My understanding no need to bump major version. Is it correct??
=> chore: bump version from 4.1.0 to 5.0.0

README.md, lib/renderer.js, test/index.js
add marked [extensions](https://marked.js.org/using_pro#extensions) support. partial #209
=> [feat]: add marked extensions support

.gitignore, package.json
As is the title. I will going to release a new version after merge this (Also I will submit another PR for bump version).
Thank you :)
=> chore(deps): update deps & replace `nyc` with `c8`

.gitignore, package.json
I'm going to publish a new version after merge this PR.
Thank you :)
=> release: v6.0.0

.github/dependabot.yml
As is the title.
dependabot is super noisy for me.
=> chore(ci): reduce dependabot pull request

package.json
- Update some dependencies
- Fixes #229 
- Others
=> release: v6.1.0

package.json
I'm going to release `v6.1.1` after merge #258
=> release: v6.1.1

lib/renderer.js, test/index.js
https://github.com/hexojs/hexo-renderer-marked/pull/264 actually not working well
=> fix: figcaption only works within figure

package.json
I want to merge https://github.com/hexojs/hexo-renderer-marked/pull/274 before release a new version.
Thank you :)
=> release: v6.3.0

lib/renderer.js
=> perf: reduce the number of regexp calls
