hexojs/hexo-renderer-marked

- lib/renderer.js
- test/index.js
In hexo configuration, if the root path is set to a sub directory, hexo
should prepend this root path to img and link of markdown syntax.
Resolves: https://github.com/hexojs/hexo/issues/1440
> Prepend root path to img and link

- lib/renderer.js
- test/index.js
Inserting links to headings directly from markdown is common practice. `[jump to title](#title)` should not become a full-blown URL on markdown rendering. It should instead be rendered as-is: `<a href="#title">jump to title</a>`.
> No prefix for anchor links

- README.md
- lib/renderer.js
- test/index.js
I find myself using descriptions lists, so I've added support for them in my Hexo setup, and want to offer it here to be included in the main repo. This will turn a [PHP Markdown style definition list](https://michelf.ca/projects/php-markdown/extra/#def-list) into the correct definition list html.
So this Markdown:
```markdown
Definition Term
:    This is the definition for the term
```
Will generate this html:
```html
<dl>
<dt>Definition Term</dt>
<dd>This is the definition for the term</dd>
</dl>
```
There is a limitation in the `<dd>`. This only supports single definitions. The above Markdown will work, but this will not:
```markdown
Definition Term
:    Definition 1
:    Definition 2
```
That Markdown will generate this html:
```html
<dl>
<dt>Definition Term<br>: Definition 1</dt> …
```
> Add support for basic description/definition lists

- lib/renderer.js
- package.json
- test/index.js
Update marked from 0.3.9 to 0.6.0 &  fixed testcode for breaking change in marked v0.4.0
* https://github.com/markedjs/marked/pull/1266
* https://github.com/markedjs/marked/pull/1250
> chore(package): update marked 0.3.9 to 0.6.1

- package.json
Set node version to 6.9 same with [hexo](https://github.com/hexojs/hexo/blob/a6dc0ea28dddad1b5f1bad7c6f86f1e0627b564a/package.json#L82).
> chore: specify node version to 6.9

- index.js
- lib/renderer.js
- package.json
Object.assign can use instead of object-assign package.
> refactor(package): delete object-assign package and use Object.assign instead of it

- .npmignore
- package.json
Specified `files` in package.jso and removed outdated `.npmignore`.
Shrinked our packed size from 4.6KB to 3.6KB.
> chore: specify files in package.json

- README.md
- index.js
- lib/renderer.js
- package.json
https://snyk.io/vuln/SNYK-JS-MARKED-451341
`sanitize:` and `tables:` options have been deprecated.
`tables:` is now part of `gfm:`.
<details><summary>Changelog</summary>
* Security
- Sanitize paragraph and text tokens #1504
- Fix ReDOS for links with backticks (issue #1493) #1515
* Breaking Changes
- Deprecate sanitize and sanitizer options #1504
- Move fences to CommonMark #1511
- Move tables to GFM #1511
- Remove tables option #1511
- Single backtick in link text needs to be escaped #1515
* Fixes
- Fix parentheses around a link #1509
- Fix headings (issue #1510) #1511
* Tests
- Run tests with correct options #1511
</details>
Closes #101
> chore(deps): update marked to ^0.7.0

- README.md
- index.js
- lib/renderer.js
- test/index.js
(Enabled by default for backward compatibility)
#61
> Add option to disable headerIds

- package.json
As part of https://github.com/hexojs/hexo/pull/3646.
@tomap has already published this change in hexo-renderer-marked@2.0.0rc1.
> chore(deps): Update hexo-util to 1.0.0

- README.md
- index.js
- lib/renderer.js
- package.json
- test/index.js
encodeURL is added in hexo-util [1.1.0](https://github.com/hexojs/hexo-util/releases/tag/1.1.0).
url_for is added in hexo-util [1.2.0](https://github.com/hexojs/hexo-util/releases/tag/1.2.0).
This feature can be enabled through `prependRoot` option, which is disabled by default.
> feat: prepend root to image path

- README.md
- index.js
- lib/renderer.js
- test/index.js
This feature is introduced due to perf cost of the `external_link` [filter](https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/after_render/external_link.js). When use in renderer, it can be applied directly to links, instead of a filter which has to first parse the whole site content to look for links.
To take advantage of the perf improvement, `external_link:` of the site config needs to be disabled.
Configuration:
``` yml
external_link:
enable: false
marked:
external_link:
enable: true
```
Some notes:
1. This feature is only applicable to `[]()` markdown syntax, not raw `<a>`.
2. This is not a duplicate hexo's [`external_link`](https://hexo.io/docs/configuration#Writing) as that works on `<a>` element, not markdown.
- hexo's `external_link` applies to every `<a>` regardless …
> feat(link): add external_link

- lib/renderer.js
- test/index.js
https://www.stephencharlesweiss.com/2019-08-22/markdown-images-alt-text-and-title/
Noticed when testing https://github.com/hexojs/hexo/issues/3879
marked escapes values of `alt` and `title` by default.
> feat: support title attribute in image element

- lib/renderer.js
- package.json
- test/index.js
This PR makes the code blocks result consistent by removing `marked.setOptions.highlight`.
More info can be found here: https://github.com/hexojs/hexo/issues/4010#issuecomment-568906344
> #### `config.highlight.enable: true`
> By default `hljs` is disabled and `wrap` is enabled. Hexo will render something likes:
> 
> ```
> <figure class="highlight sh">
>   <table>
>     ...
>   </table>
> </figure>
> ```
> 
> #### `config.highlight.enable: false` with `hexo-renderer-marked`
> Since highlight has been disabled, the `before_post_render` filter will do nothing and leave everything to helpers (powered by nunjucks) and marked (from hexo-renderer-marked).
> 
> `code()` helper [is designed](https://github.com/hexojs/hexo/blob/8fae1a6a98d9fd6ffb6f07ab549a4cf723d8b032/lib/plugins/tag/code.js#L136-L …
> refactor: remove marked.setOptions.highlight

- index.js
- lib/renderer.js
- test/index.js
This PR reverts #132 by using synchronous again, as hexo has a `markdown()` helper which require markdown renderer to be synchronous.
> revert: feat: promisify

- .travis.yml
Node 13 is retained for now for debugging (ref https://github.com/hexojs/hexo/issues/4260), to be deprecated in [June 2020](https://github.com/nodejs/Release#release-schedule).
> ci(travis): drop Node 8 and add Node 14

- README.md
- index.js
- lib/renderer.js
- test/index.js
See also [Lazy loading via attribute for images & iframes](https://caniuse.com/#feat=loading-lazy-attr)
> feat: lazyload

- .travis.yml
- README.md
- lib/renderer.js
- test/index.js
- test/source/_posts/foo.md
Fixes https://github.com/hexojs/hexo/issues/4454 cc @v-tawe 
How to use:
``` yml
#_config.yml
post_asset_folder: true
marked:
prependRoot: true
postAsset: true
```
Based on [`asset_img`](https://github.com/hexojs/hexo/blob/382b0deef4ea6906a58c7828a70d4b3bebb5b2da/lib/plugins/tag/asset_img.js) tag plugin.
> feat(image): postAsset to prepend post's relative path

- lib/renderer.js
- test/index.js
[`link`](https://marked.js.org/#/USING_PRO.md#inline-level-renderer-methods) renderer method couldn't discern whether a link is inside `[]()`, `<>`, `http://example.com` or `www.example.com`.
Meanwhile, [`url`](https://marked.js.org/#/USING_PRO.md#inline-level-tokenizer-methods) tokenizer is the method responsible for detecting `http://example.com` or `www.example.com`, so `autolink` option is more suitable there. (marked doesn't detect `example.com`, if a link doesn't starts with protocol (e.g. `http://`), a link must starts with www to be detected).
Fixes #139
> fix: autolink option should not apply on markdown syntax

- lib/renderer.js
- test/index.js
Closes https://github.com/hexojs/hexo/issues/4502
> fix: handle invalid URL

- README.md
- index.js
- test/index.js
easier than https://hexo.io/api/rendering#Disable-Nunjucks-tags
> feat: disableNunjucks option

- README.md
- index.js
- test/index.js
built-in [option](https://marked.js.org/using_advanced#options) of marked, this is just exposing to renderer config.
> feat: mangle option

- lib/renderer.js
- test/index.js
previously it was assumed that all posts are in top folder of `source/_posts/`, but in reality, posts could be in any subfolder of `_posts/`.
Closes #170 cc @smalltimer
How to test:
1. `$ npm install hexo-renderer-marked@curbengh/hexo-renderer-marked#postasset-subfolder`
2. `hexo clean`
3. `hexo server`
> fix(postAsset): post may be in a subfolder

- README.md
- index.js
- lib/renderer.js
- test/index.js
Requested by https://github.com/hexojs/hexo-renderer-marked/pull/60#issuecomment-690033242 @sinkcup
Based on #60 credit @mdluo
> feat: anchorAlias option to set custom header id

- README.md
- index.js
- lib/renderer.js
- test/index.js
This provides an option for `<dl>` support. Currently, the option is enabled by default for backward compatibility, but disable it will gain a lot of performance, thus here goes the PR. We should disable it v4 by default for better performance.
> feat: add descriptionLists options

- package.json
We merged marked `v2.0.0`.
> #183 
As marked v2.0.0's release note, tokenizers were changed.
> https://github.com/markedjs/marked/releases/tag/v2.0.0
IMHO we should bump the major version.
Thank you :)
> release: v4.0.0

- .github/workflows/linter.yml
- .github/workflows/tester.yml
> Support Node v16

- README.md
- index.js
- lib/renderer.js
- package.json
- test/index.js
Non breacking new feature (disabled by default)
Will need a Minor version bump.
Once done, the plan is to enable it by default, to be safe by default :)
> Add DOMPurify to sanitize HTML

- lib/renderer.js
The many lines of the current `Tokenizer.url` (extends from MarkedTokenizer) method seems just copy from marked's `Tokenizer.url` method.
It is very costly when update marked dependency.
I think just call super class method is enough.
> refactor: call parent class url tokenizer method

- README.md
- marked's internal escape() is no longer exported
- continue #214
> docs(tokenizer): utilise escapeHTML()

- README.md
- package.json
> dosc: `http` to `https` and use `example.com` for example domains

- lib/renderer.js
- test/index.js
Fix https://github.com/hexojs/hexo-renderer-marked/issues/246
> fix: use unescaped heading text

- README.md
- lib/renderer.js
- test/index.js
Append `figcaption` element after each image.
This feature is supported by other renderers, e.g. hexo-renderer-pandoc.
https://pandoc.org/MANUAL.html#extension-implicit_figures
> feat: new option figcaption

- README.md
- lib/renderer.js
Background:
The [marked-alert](https://github.com/bent10/marked-extensions/tree/main/packages/alert) extension enables usage of [GFM alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
To use this extension (and maybe some others) the current `marked:extensions` filter is not enough since it only provides the `extensions` property but the altert extension also requires `walkTokens` to be set in `marked.use(...)`.
This PR adds a `marked:use` filter allowing the usage of the `marked.use` function in a theme.
Usage example:
```js
const markedAlert = require('marked-alert');
hexo.extend.filter.register('marked:use', function (markedUse) {
markedUse(markedAlert());
});
```
> Added filter marked:use for direct access to the marked.use function

- .github/workflows/linter.yml
- .github/workflows/tester.yml
`actions/cache@v1` will soon be deprecated. The PR bumps the version of a few actions. The PR also excludes the macOS + Node.js 14 matrix (As there is no Node.js 14 arm64 build).
https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
> ci: bump `actions/cache`

- README.md
- package.json
> release: v7.0.0

- lib/renderer.js
- test/index.js
Reset the internal configuration used when `marked.use` to prevent functions from self-referencing
fix #310
> fix: Maximum call stack size exceeded

- README.md
incorrect after marked v15 update #305
> docs(renderer): remove link to oudated line
